import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<NextUIProvider>
					<NextThemesProvider attribute='class'>{children}</NextThemesProvider>
				</NextUIProvider>
			</body>
		</html>
	);
}
